### ISSUE TITLE
GPU usage error

### ISSUE THREAD

**Issue by chenxqdu** [aws-samples/host-yolov8-on-sagemaker-endpoint#24]
When I deployed the model with ml.m5 as in sample it worked well, I changed to use ml.g5 instance for deployment, the invoke_endpoint raised error and what I got in cloudwatch was :

```
2024-10-15T10:42:51.928Z
AttributeError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetComputeRunningProcesses_v3
	
2024-10-15T10:42:51.928Z
During handling of the above exception, another exception occurred:
	
2024-10-15T10:42:51.928Z
Traceback (most recent call last):
  File "ts/metrics/metric_collector.py", line 27, in <module>
    system_metrics.collect_all(sys.modules['ts.metrics.system_metrics'], arguments.gpu)
  File "/opt/conda/lib/python3.8/site-packages/ts/metrics/system_metrics.py", line 119, in collect_all
    value(num_of_gpu)
  File "/opt/conda/lib/python3.8/site-packages/ts/metrics/system_metrics.py", line 90, in gpu_utilization
    statuses = list_gpus.device_statuses()
  File "/opt/conda/lib/python3.8/site-packages/nvgpu/list_gpus.py", line 75, in device_statuses
    return [device_status(device_index) for device_index in range(device_count)]
  File "/opt/conda/lib/python3.8/site-packages/nvgpu/list_gpus.py", line 75, in <listcomp>
    return [device_status(device_index) for device_index in range(device_count)]
  File "/opt/conda/lib/python3.8/site-packages/nvgpu/list_gpus.py", line 19, in device_status
    nv_procs = nv.nvmlDeviceGetComputeRunningProcesses(handle)
  File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 2608, in nvmlDeviceGetComputeRunningProcesses
    return nvmlDeviceGetComputeRunningProcesses_v3(handle);
  File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 2576, in nvmlDeviceGetComputeRunningProcesses_v3
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetComputeRunningProcesses_v3")
  File "/opt/conda/lib/python3.8/site-packages/pynvml/nvml.py", line 853, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
	
2024-10-15T10:42:53.433Z
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found
```

I searched and added "pynvml==11.4.1" in the requirements.txt, the above error disappeared but the invoke_endpoint still returned error, this time there wasn't any clue in cloudwatch. Can anyone help to check?

**Comment by chenxqdu** [comment]
submit a pull request for fix https://github.com/aws-samples/host-yolov8-on-sagemaker-endpoint/pull/25

**Comment by shahromil16** [comment]
PR approved and merged
